# Generated by Django 4.0.3 on 2022-05-28 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_permit', '0002_vechicle_rename_fhone_number_owner_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='VechicleDetail',
            fields=[
                ('vehicle_number', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='Vehicle Plate Number')),
                ('vehicle_name', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=15, verbose_name='Vehicle Model')),
                ('chasis', models.CharField(max_length=20, verbose_name='Chasis Number')),
                ('engine', models.CharField(max_length=20, verbose_name='Engine Number')),
                ('vehicle_type', models.CharField(max_length=16, verbose_name='Type of Vehicle')),
            ],
        ),
        migrations.DeleteModel(
            name='Vechicle',
        ),
        migrations.AlterField(
            model_name='owner',
            name='citizen_of',
            field=models.CharField(max_length=10, verbose_name='select the Country'),
        ),
        migrations.AddField(
            model_name='vechicledetail',
            name='owner',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='vehicle_permit.owner'),
        ),
    ]
